### ISSUE TITLE
提几点建议哈

### ISSUE THREAD

**Issue by Svenshen** [cjbi/wetech-admin#2]
1.建议集成Lombok减少代码量
2.Controller层是否不要撰写页面代码，页面渲染还是交给Thymeleaf
3.持久层框架实现可选用Hibernate，Hibernate有自动建表功能，真的很方便
4.权限读取那块可直接使用@ManyToMany注解映射实现
5.JS、CSS等前端框架是否也可以使用maven导入，便于版本管理

**Comment by 378056350** [comment]
> 1.建议集成Lombok减少代码量
> 2.Controller层是否不要撰写页面代码，页面渲染还是交给Thymeleaf
> 3.持久层框架实现可选用Hibernate，Hibernate有自动建表功能，真的很方便
> 4.权限读取那块可直接使用@manytomany注解映射实现
> 5.JS、CSS等前端框架是否也可以使用maven导入，便于版本管理

你的建议对我很受用, 不过我觉得写这个项目的人只是为了练手, 估摸着这个项目他是不会加了

**Comment by cjbi** [comment]
> > 1.建议集成Lombok减少代码量
> > 2.Controller层是否不要撰写页面代码，页面渲染还是交给Thymeleaf
> > 3.持久层框架实现可选用Hibernate，Hibernate有自动建表功能，真的很方便
> > 4.权限读取那块可直接使用@manytomany注解映射实现
> > 5.JS、CSS等前端框架是否也可以使用maven导入，便于版本管理
> 
> 你的建议对我很受用, 不过我觉得写这个项目的人只是为了练手, 估摸着这个项目他是不会加了
之前确实是练手的，准备再更新一把2.0版本，计划：
1. 使用Lombok
2. 准备前后端分离，不存在后端渲染模板
3. 还是使用MyBatis，不过是用自己封装过的，https://github.com/cjbi/mybatis-ext 
4. 权限这块设计准备重新考虑一下
5. 通过webjars引入后端资源，支持版本管理
另外，前端是采用Ant Design pro vue

**Comment by 378056350** [comment]
> > > 1.建议集成Lombok减少代码量
> > > 2.Controller层是否不要撰写页面代码，页面渲染还是交给Thymeleaf
> > > 3.持久层框架实现可选用Hibernate，Hibernate有自动建表功能，真的很方便
> > > 4.权限读取那块可直接使用@manytomany注解映射实现
> > > 5.JS、CSS等前端框架是否也可以使用maven导入，便于版本管理
> > 
> > 
> > 你的建议对我很受用, 不过我觉得写这个项目的人只是为了练手, 估摸着这个项目他是不会加了
> 
> 之前确实是练手的，准备再更新一把2.0版本，计划：
> 
> 1. 使用Lombok
> 2. 准备前后端分离，不存在后端渲染模板
> 3. 还是使用MyBatis，不过是用自己封装过的，https://github.com/cjbi/mybatis-ext
> 4. 权限这块考虑重新设计一把
> 5. 通过webjars引入前端资源，支持版本管理
>    另外，前端是采用Ant Design pro vue

哇哦, 走全栈的路子?

**Comment by cjbi** [comment]
> > > > 1.建议集成Lombok减少代码量
> > > > 2.Controller层是否不要撰写页面代码，页面渲染还是交给Thymeleaf
> > > > 3.持久层框架实现可选用Hibernate，Hibernate有自动建表功能，真的很方便
> > > > 4.权限读取那块可直接使用@manytomany注解映射实现
> > > > 5.JS、CSS等前端框架是否也可以使用maven导入，便于版本管理
> > > 
> > > 
> > > 你的建议对我很受用, 不过我觉得写这个项目的人只是为了练手, 估摸着这个项目他是不会加了
> > 
> > 
> > 之前确实是练手的，准备再更新一把2.0版本，计划：
> > 
> > 1. 使用Lombok
> > 2. 准备前后端分离，不存在后端渲染模板
> > 3. 还是使用MyBatis，不过是用自己封装过的，https://github.com/cjbi/mybatis-ext
> > 4. 权限这块考虑重新设计一把
> > 5. 通过webjars引入前端资源，支持版本管理
> >    另外，前端是采用Ant Design pro vue
> 
> 哇哦, 走全栈的路子?

没必要分得太细，都差不多🤔

**Comment by 378056350** [comment]
> > > > > 1.建议集成Lombok减少代码量
> > > > > 2.Controller层是否不要撰写页面代码，页面渲染还是交给Thymeleaf
> > > > > 3.持久层框架实现可选用Hibernate，Hibernate有自动建表功能，真的很方便
> > > > > 4.权限读取那块可直接使用@manytomany注解映射实现
> > > > > 5.JS、CSS等前端框架是否也可以使用maven导入，便于版本管理
> > > > 
> > > > 
> > > > 你的建议对我很受用, 不过我觉得写这个项目的人只是为了练手, 估摸着这个项目他是不会加了
> > > 
> > > 
> > > 之前确实是练手的，准备再更新一把2.0版本，计划：
> > > 
> > > 1. 使用Lombok
> > > 2. 准备前后端分离，不存在后端渲染模板
> > > 3. 还是使用MyBatis，不过是用自己封装过的，https://github.com/cjbi/mybatis-ext
> > > 4. 权限这块考虑重新设计一把
> > > 5. 通过webjars引入前端资源，支持版本管理
> > >    另外，前端是采用Ant Design pro vue
> > 
> > 
> > 哇哦, 走全栈的路子?
> 
> 没必要分得太细，都差不多🤔

也是, 共勉
